{
 "title": "RuuviTag Prometheus Dashboard",
 "description": "Dashboard for ruuvitag prometheus exporter: https://github.com/arimkevi/ruuvi-prometheus-scraper",
 "tags": [
  "Prometheus",
  "RuuviTag"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ruuvi_temperature_c", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Temperature history",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ruuvi_temperature_c", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Humitidy",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ruuvi_humidity_percent", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Humidity history",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "ruuvi_humidity_percent", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ruuvi_pressure_hpa", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Pressure history",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "yaxes": [
    { "format": "pressurembar" }
   ],
   "targets": [
    { "expr": "ruuvi_pressure_hpa", "legendFormat": "{{location}}" }
   ]
  }
 ]
}